apiVersion: v1
kind: Namespace
metadata:
  name: crossplane-system
---
apiVersion: v1
kind: Secret
metadata:
  namespace: crossplane-system
  name: example-cloudian-secret
type: Opaque
data:
  # E.g. Basic c3lzYWRtaW46cGFzc3dvcmQ=
  # auth-header: BASE64ENCODED_PROVIDER_CREDS
---
apiVersion: cloudian.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: example
spec:
  authHeader:
    secretRef:
      namespace: crossplane-system
      name: example-cloudian-secret
      key: auth-header
    source: Secret
  endpoint: https://s3-admin.company.com:19443
