---
name: Lint PR
on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

permissions:
  contents: read
jobs:
  trigger:
    uses: statnett/github-workflows/.github/workflows/lint-pr.yaml@ae2c928a6e9069d4cdba65938a15d791973c2f41 # main
    permissions:
      pull-requests: write
      statuses: write
