---
name: Release Please
on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
jobs:
  trigger:
    uses: statnett/github-workflows/.github/workflows/release-please.yaml@ae2c928a6e9069d4cdba65938a15d791973c2f41 # main
    secrets: inherit
    permissions:
      contents: write
      pull-requests: write
